services:
  - type: web
    name: your-app
    env: node
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && nest build
    startCommand: npm run start:prod
    disk:
      name: data
      mountPath: /var/data
